### ISSUE TITLE
Manejo del repo

### ISSUE THREAD

**Issue by galloramiro** [Arzanico/geoMelt_App#2]
Separaría el repo en:
- Master (protegida)
- Develop (protegida y default)
- features branchs

**Master** tendría el código que estaría en producción.     
**Develop** sería sobre la que se harían todos los PR's, y de la cual se sacarian los feature branchs. De esta manera, antes de cambiar las cosas probamos que ande todo bien.   
**Feature branch** estas estarían relacionadas a una US, a un Issue y se podrían nombrar de la siguiente manera `NIssue-titulo-descriptivo` ej: `151-fix-coordinates-bug-in-kml-api`  

De esta manera podemos traquear el trabajo y entender que se esta haciendo.

**Comment by Arzanico** [comment]
Protegido el Branch "master"
Creado el branch Develop con las propiedades de "default" y "protegido"
